import colors from 'vuetify/es5/util/colors'
export default {
  breakpoint: {
    scrollBarWidth: 16,
    thresholds: {
      xs: 600,
      sm: 960,
      md: 1280,
      lg: 1920,
    },
    mobileBreakpoint: 900,
  },
  icons: {
    iconfont: 'mdiSvg',
    values: {},
  },
  theme: {
    dark: false,
    default: 'dark',
    disable: false,
    options: {
      cspNonce: undefined,
      customProperties: true,
      minifyTheme: undefined,
      themeCache: undefined,
    },
    themes: {
      dark: {
        primary: '#0f63e6',
        secondary: '#4fa1ff',
        accent: colors.grey.darken3,
        info: colors.teal.lighten1,
        warning: colors.amber.base,
        error: colors.deepOrange.accent4,
        success: colors.green.accent3,
        black: '#121212',
        white: '#FFFFFF',
        contrast: '#121212',
        basic: '#FFF',
      },
      light: {
        primary: '#0f63e6',
        secondary: '#0055b5',
        accent: '#8F2D56',
        info: '#73D2DE',
        warning: '#FFBC42',
        error: '#FF5252',
        success: '#4CAF50',
        contrast: '#FFF',
        basic: '#121212',
        purple: '#554d84',
        orange: '#f9b978',
        darkgrey: '#3f3d44',
        cyan: '#6ad4ec',
        darkblue: '#1b3b52',
        black: '#383333',
        lightred: '#fe3e4b',
        red: '#d82435',
        darkred: '#d10834',
        blue: '#2cb4ff',
        lightgreen: '#63ceb2',
        lightorange: '#ffb95c',
      },
    },
  },
  defaultAssets: false,
}
